# Generated by Django 6.0.3 on 2026-04-28 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('time_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('hvac', 'HVAC'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning'), ('installation', 'Installation'), ('repair', 'Repair'), ('other', 'Other')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('job_address', models.TextField(blank=True, help_text='Full address of the job location.')),
                ('location', models.CharField(blank=True, max_length=300)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geofence_radius', models.PositiveIntegerField(blank=True, help_text='Radius in meters to verify location.', null=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('require_selfie', models.BooleanField(default=False)),
                ('require_before_after_photos', models.BooleanField(default=False)),
                ('employee_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company')),
                ('job_site', models.ForeignKey(blank=True, help_text='Link to an established job site, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='time_tracking.jobsite')),
                ('time_log', models.OneToOneField(blank=True, help_text='The time log associated with this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='time_tracking.timelog')),
            ],
            options={
                'ordering': ['due_date', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
