# Generated by Django 6.0.5 on 2026-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_travel_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
