# Generated by Django 6.0.5 on 2026-06-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/end_photos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='face_match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='face_match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='start_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/start_photos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
