# Generated by Django 6.0.5 on 2026-06-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("tasks", "0011_task_end_photo_task_face_match_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="blocking_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("fulfilled", "Fulfilled"),
                    ("partial", "Partial"),
                    ("missing", "Missing"),
                    ("pending_transfer", "Pending Transfer"),
                ],
                default="fulfilled",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TaskRequiredItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_needed", models.PositiveIntegerField(default=1)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "inventory_item")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="required_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks_requiring",
                through="tasks.TaskRequiredItem",
                to="inventory.inventoryitem",
            ),
        ),
    ]
