# Generated by Django 6.0.3 on 2026-04-28 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geofence_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_sites', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('geofence_radius', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('clock_in', models.DateTimeField()),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_address', models.TextField(blank=True)),
                ('clock_in_notes', models.TextField(blank=True)),
                ('clock_in_photo', models.ImageField(blank=True, null=True, upload_to='time_logs/photos/')),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_address', models.TextField(blank=True)),
                ('clock_out_notes', models.TextField(blank=True)),
                ('clock_out_photo', models.ImageField(blank=True, null=True, upload_to='time_logs/photos/')),
                ('distance_from_site_meters', models.IntegerField(blank=True, null=True)),
                ('geofence_passed', models.BooleanField(default=False)),
                ('admin_override_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('face_match_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('mismatch', 'Mismatch'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('manual_hours_correction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch'), ('short', 'Short'), ('personal', 'Personal')], default='lunch', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='time_tracking.timelog')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='job_photos/')),
                ('photo_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('progress', 'Progress')], max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('time_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='time_tracking.timelog')),
            ],
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee', 'work_date'], name='time_tracki_employe_d88427_idx'),
        ),
    ]
