# Generated by Django 6.0.4 on 2026-05-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("employees", "0002_initial"),
        ("time_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="location",
            name="geofence_polygon",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="location",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("job_site", "Job Site"),
                    ("client_site", "Client Site"),
                    ("warehouse", "Warehouse"),
                    ("other", "Other"),
                ],
                default="office",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_logs",
                to="time_tracking.location",
            ),
        ),
        migrations.CreateModel(
            name="LocationZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#4F46E5", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_zones",
                        to="companies.company",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="zones", to="time_tracking.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permitted_locations",
                        to="employees.employee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permitted_employees",
                        to="time_tracking.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "location")},
            },
        ),
    ]
