# Generated by Django 6.0.5 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracking", "0004_phase7_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="loc_polygon_gin_idx",
        ),
        migrations.AddField(
            model_name="break",
            name="duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="break",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="break",
            name="break_type",
            field=models.CharField(
                choices=[
                    ("tea", "Tea Break"),
                    ("lunch", "Lunch Break"),
                    ("personal", "Personal Break"),
                ],
                default="tea",
                max_length=20,
            ),
        ),
    ]
