# Generated by Django 6.0.5 on 2026-06-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_shift_enforcement_mode"),
        ("employees", "0006_employee_bank_details_employee_currency_and_more"),
        ("payroll", "0002_payrollrecord_uk_paye_ot_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=10)),
                ("currency_symbol", models.CharField(max_length=10)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                ("country", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="Generated", max_length=50)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_generations",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_generations",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "basic_percentage",
                    models.DecimalField(decimal_places=2, default=40, max_digits=5),
                ),
                (
                    "hra_percentage",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                (
                    "pf_percentage",
                    models.DecimalField(decimal_places=2, default=12, max_digits=5),
                ),
                (
                    "esi_percentage",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
                ),
                ("tax_formula", models.TextField(blank=True, null=True)),
                ("pension_formula", models.TextField(blank=True, null=True)),
                ("overtime_formula", models.TextField(blank=True, null=True)),
                ("allowances", models.JSONField(blank=True, default=dict)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_rules",
                        to="companies.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.currencymaster",
                    ),
                ),
            ],
        ),
    ]
