# Generated by Django 6.0.5 on 2026-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_currencymaster_payrollgeneration_payrollrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='mileage_reimbursement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
