# Generated by Django 6.0.5 on 2026-06-04 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_shift_enforcement_mode'),
        ('employees', '0006_employee_bank_details_employee_currency_and_more'),
        ('inventory', '0001_initial'),
        ('payroll', '0003_currencymaster_payrollgeneration_payrollrule'),
        ('tasks', '0012_task_blocking_reason_task_inventory_status_and_more'),
        ('time_tracking', '0006_timelog_tl_status_date_idx_timelog_tl_emp_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_mile_usd', models.DecimalField(decimal_places=4, default=0.67, max_digits=7)),
                ('rate_per_mile_gbp_first', models.DecimalField(decimal_places=4, default=0.45, max_digits=7)),
                ('rate_per_mile_gbp_after', models.DecimalField(decimal_places=4, default=0.25, max_digits=7)),
                ('uk_mileage_threshold', models.IntegerField(default=10000)),
                ('uk_tax_year_start_month', models.IntegerField(default=4)),
                ('uk_tax_year_start_day', models.IntegerField(default=6)),
                ('rate_per_km_inr', models.DecimalField(decimal_places=4, default=3.5, max_digits=7)),
                ('require_receipt_above_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Require receipt when trip exceeds this many miles', max_digits=8, null=True)),
                ('auto_approve_below_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-approve trips under this many miles', max_digits=8, null=True)),
                ('max_single_trip_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed miles for a single trip', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_policy', to='companies.company')),
            ],
            options={
                'verbose_name': 'Mileage Policy',
                'verbose_name_plural': 'Mileage Policies',
            },
        ),
        migrations.CreateModel(
            name='MileageTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('from_location_name', models.CharField(blank=True, max_length=300)),
                ('to_location_name', models.CharField(blank=True, max_length=300)),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_lng', models.FloatField(blank=True, null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_lng', models.FloatField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('distance_miles', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('purpose', models.CharField(choices=[('task_travel', 'Task Travel'), ('tool_collection', 'Tool Collection'), ('emergency', 'Emergency'), ('training', 'Training'), ('client_visit', 'Client Visit')], default='task_travel', max_length=30)),
                ('jurisdiction', models.CharField(choices=[('US', 'United States (IRS)'), ('UK', 'United Kingdom (HMRC)'), ('IN', 'India')], default='US', max_length=2)),
                ('tax_year', models.CharField(blank=True, max_length=9)),
                ('ytd_miles_before', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('miles_at_high_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('miles_at_low_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('rate_applied', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_taxable_excess', models.BooleanField(default=False)),
                ('taxable_excess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('employee_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='mileage/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mileage_trips', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_trips', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_trips', to='employees.employee')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_trips_from', to='time_tracking.jobsite')),
                ('linked_payroll_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_trips', to='payroll.payrollrecord')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_trips', to='tasks.task')),
                ('linked_timelog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_trips', to='time_tracking.timelog')),
                ('linked_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_trips', to='inventory.inventorytransfer')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_trips_to', to='time_tracking.jobsite')),
            ],
            options={
                'verbose_name': 'Mileage Trip',
                'verbose_name_plural': 'Mileage Trips',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MileageYTDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(choices=[('US', 'United States (IRS)'), ('UK', 'United Kingdom (HMRC)'), ('IN', 'India')], max_length=2)),
                ('tax_year', models.CharField(max_length=9)),
                ('total_miles', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('miles_at_high_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('miles_at_low_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_reimbursed_gbp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('threshold_crossed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_ytd_trackers', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_ytd', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Mileage YTD Tracker',
                'verbose_name_plural': 'Mileage YTD Trackers',
                'unique_together': {('company', 'employee', 'jurisdiction', 'tax_year')},
            },
        ),
    ]
