# Generated by Django 6.0.3 on 2026-04-28 06:52

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('company_name', models.CharField(max_length=255)),
                ('display_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('primary_country', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom')], default='US', max_length=2)),
                ('default_state', models.CharField(blank=True, max_length=100, null=True)),
                ('geofence_enabled', models.BooleanField(default=True)),
                ('geofence_radius_meters', models.PositiveIntegerField(default=200)),
                ('geofence_strict_mode', models.BooleanField(default=True)),
                ('geofence_admin_override', models.BooleanField(default=True)),
                ('compliance_mode', models.CharField(choices=[('strict', 'Strict'), ('flexible', 'Flexible')], default='strict', max_length=20)),
                ('allowed_countries', models.JSONField(blank=True, default=list)),
                ('team_size', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_modules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
