# Generated by Django 6.0.5 on 2026-06-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_shift_enforcement_mode'),
        ('employees', '0004_employee_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_availability',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PresenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(blank=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_logs', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
    ]
