# Generated by Django 6.0.5 on 2026-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_current_availability_employee_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="employee",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="payroll_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="tax_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
